VioRentals.Web/Controllers/AuthenticateController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using VioRentals.Core.DTOs;
using VioRentals.Infrastructure.Repositories.Interfaces;

namespace VioRentals.Web.Controllers
{
    public class AuthenticateController : Controller
    {
        public async Task<ActionResult> Login([FromForm] LoginDto loginDto)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:7071/api/");
                    JsonContent content = JsonContent.Create(loginDto);
                    await client.PostAsync("Users/login", content);
                }

                return RedirectToAction("Index", "Customers");
            }
            return BadRequest(ModelState);
        }

        public async Task<ActionResult> Register([FromForm] RegisterDto registerDto)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:7071/api/");
                    JsonContent content = JsonContent.Create(registerDto);
                    await client.PostAsync("Users/register", content);
                }

                return RedirectToAction("Index", "Customers");
            }
            return BadRequest(ModelState);
        }

        public async Task<ActionResult> GetAll()
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:7071/api/");
                HttpResponseMessage response = await client.GetAsync("Users/all");
                return Ok(response.Content);
            }
        }
    }
}

VioRentals.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VioRentals.Web.Models;

namespace VioRentals.Web.Controllers
{
	[AllowAnonymous]
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

        #region testing_purposes
        public IActionResult Register()
		{
			return View();
		}

		public IActionResult Login() 
		{
			return View();
		}
        #endregion

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

VioRentals.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!-- Features -->
<div class="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
    <!-- Tab Nav -->
    <nav class="max-w-6xl mx-auto grid grid-cols-2 sm:grid-cols-3 gap-2 sm:gap-4" aria-label="Tabs" role="tablist">
        <button type="button" class="hs-tab-active:bg-gray-100 hs-tab-active:hover:border-transparent text-center md:text-left hover:bg-gray-100 p-3 md:p-5 rounded-xl dark:hs-tab-active:bg-white/[.05] dark:hover:bg-gray-700 active" id="tabs-with-card-item-1" data-hs-tab="#tabs-with-card-1" aria-controls="tabs-with-card-1" role="tab">
            <span class="md:flex">
                <svg class="hidden md:block flex-shrink-0 md:mt-2 h-6 w-6 hs-tab-active:text-blue-600 text-gray-500 dark:hs-tab-active:text-blue-500 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M5.5 2A3.5 3.5 0 0 0 2 5.5v5A3.5 3.5 0 0 0 5.5 14h5a3.5 3.5 0 0 0 3.5-3.5V8a.5.5 0 0 1 1 0v2.5a4.5 4.5 0 0 1-4.5 4.5h-5A4.5 4.5 0 0 1 1 10.5v-5A4.5 4.5 0 0 1 5.5 1H8a.5.5 0 0 1 0 1H5.5z" />
                    <path d="M16 3a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                </svg>
                <span class="md:grow md:ml-5">
                    <span class="hs-tab-active:text-blue-600 block font-semibold text-gray-800 dark:hs-tab-active:text-blue-500 dark:text-gray-200">UI Design</span>
                    <span class="hidden lg:block mt-2 text-gray-800 dark:text-gray-200">Made in Tailwind - Preline. Simple, clear, resposive.</span>
                </span>
            </span>
        </button>

        <button type="button" class="hs-tab-active:bg-gray-100 hs-tab-active:hover:border-transparent text-center md:text-left hover:bg-gray-100 p-3 md:p-5 rounded-xl dark:hs-tab-active:bg-white/[.05] dark:hover:bg-gray-700" id="tabs-with-card-item-2" data-hs-tab="#tabs-with-card-2" aria-controls="tabs-with-card-2" role="tab">
            <span class="md:flex">
                <svg class="hidden md:block flex-shrink-0 md:mt-2 h-6 w-6 hs-tab-active:text-blue-600 text-gray-500 dark:hs-tab-active:text-blue-500 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z" />
                </svg>
                <span class="md:grow md:ml-5">
                    <span class="hs-tab-active:text-blue-600 block font-semibold text-gray-800 dark:hs-tab-active:text-blue-500 dark:text-gray-200">Dark mode supported</span>
                    <span class="hidden lg:block mt-2 text-gray-800 dark:text-gray-200">Dark mode applied manually at the navbar.</span>
                </span>
            </span>
        </button>

        <button type="button" class="hs-tab-active:bg-gray-100 hs-tab-active:hover:border-transparent text-center md:text-left hover:bg-gray-100 p-3 md:p-5 rounded-xl dark:hs-tab-active:bg-white/[.05] dark:hover:bg-gray-700" id="tabs-with-card-item-3" data-hs-tab="#tabs-with-card-3" aria-controls="tabs-with-card-3" role="tab">
            <span class="md:flex">
                <svg class="hidden md:block flex-shrink-0 md:mt-2 h-6 w-6 hs-tab-active:text-blue-600 text-gray-500 dark:hs-tab-active:text-blue-500 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M5.52.359A.5.5 0 0 1 6 0h4a.5.5 0 0 1 .474.658L8.694 6H12.5a.5.5 0 0 1 .395.807l-7 9a.5.5 0 0 1-.873-.454L6.823 9.5H3.5a.5.5 0 0 1-.48-.641l2.5-8.5zM6.374 1 4.168 8.5H7.5a.5.5 0 0 1 .478.647L6.78 13.04 11.478 7H8a.5.5 0 0 1-.474-.658L9.306 1H6.374z" />
                </svg>
                <span class="md:grow md:ml-5">
                    <span class="hs-tab-active:text-blue-600 block font-semibold text-gray-800 dark:hs-tab-active:text-blue-500 dark:text-gray-200">Microservices</span>
                    <span class="hidden lg:block mt-2 text-gray-800 dark:text-gray-200">3 independent mocroservices made in Rust :o</span>
                </span>
            </span>
        </button>
    </nav>
    <!-- End Tab Nav -->
    <!-- Tab Content -->
    <div class="mt-12 md:mt-16">
        <div id="tabs-with-card-1" role="tabpanel" aria-labelledby="tabs-with-card-item-1">
            <!-- Devices -->
            <div class="max-w-[1140px] lg:pb-32 relative">
                <!-- Mobile Device -->
                <figure class="hidden absolute bottom-0 left-0 z-[2] max-w-full w-60 h-auto mb-20 ml-20 lg:block">
                    <div class="p-1.5 bg-gray-100 rounded-3xl shadow-[0_2.75rem_5.5rem_-3.5rem_rgb(45_55_75_/_20%),_0_2rem_4rem_-2rem_rgb(45_55_75_/_30%),_inset_0_-0.1875rem_0.3125rem_0_rgb(45_55_75_/_20%)] dark:bg-gray-700 dark:shadow-[0_2.75rem_5.5rem_-3.5rem_rgb(0_0_0_/_20%),_0_2rem_4rem_-2rem_rgb(0_0_0_/_30%),_inset_0_-0.1875rem_0.3125rem_0_rgb(0_0_0_/_20%)]">
                        <img class="max-w-full h-auto rounded-[1.25rem]" src="./img/img9.jpg" alt="Image Description">
                    </div>
                </figure>
                <!-- End Mobile Device -->
                <!-- Browser Device -->
                <figure class="ml-auto mr-20 relative z-[1] max-w-full w-[50rem] h-auto rounded-b-lg shadow-[0_2.75rem_3.5rem_-2rem_rgb(45_55_75_/_20%),_0_0_5rem_-2rem_rgb(45_55_75_/_15%)] dark:shadow-[0_2.75rem_3.5rem_-2rem_rgb(0_0_0_/_20%),_0_0_5rem_-2rem_rgb(0_0_0_/_15%)]">
                    <div class="relative flex items-center max-w-[50rem] bg-white border-b border-gray-100 rounded-t-lg py-2 px-24 dark:bg-gray-800 dark:border-gray-700">
                        <div class="flex space-x-1 absolute top-2/4 left-4 -translate-y-1">
                            <span class="w-2 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></span>
                            <span class="w-2 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></span>
                            <span class="w-2 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></span>
                        </div>
                        <div class="flex justify-center items-center w-full h-full bg-gray-200 text-[.25rem] text-gray-800 rounded-sm sm:text-[.5rem] dark:bg-gray-700 dark:text-gray-200">www.preline.co</div>
                    </div>

                    <div class="bg-gray-800 rounded-b-lg">
                        <img class="max-w-full h-auto rounded-b-lg" src="./img/img8.jpg" alt="Image Description">
                    </div>
                </figure>
                <!-- End Browser Device -->
            </div>
            <!-- End Devices -->
        </div>

        <div id="tabs-with-card-2" class="hidden" role="tabpanel" aria-labelledby="tabs-with-card-item-2">
            <!-- Devices -->
            <div class="max-w-[1140px] lg:pb-32 relative">
                <!-- Mobile Device -->
                <figure class="hidden absolute bottom-0 left-0 z-[2] max-w-full w-60 h-auto mb-20 ml-20 lg:block">
                    <div class="p-1.5 bg-gray-700 rounded-3xl shadow-[0_2.75rem_5.5rem_-3.5rem_rgb(0_0_0_/_20%),_0_2rem_4rem_-2rem_rgb(0_0_0_/_30%),_inset_0_-0.1875rem_0.3125rem_0_rgb(0_0_0_/_20%)]">
                        <img class="max-w-full h-auto rounded-[1.25rem]" src="./img/img11.jpg" alt="Image Description">
                    </div>
                </figure>
                <!-- End Mobile Device -->
                <!-- Browser Device -->
                <figure class="ml-auto mr-20 relative z-[1] max-w-full w-[50rem] h-auto rounded-b-lg shadow-shadow-[0_2.75rem_3.5rem_-2rem_rgb(0_0_0_/_20%),_0_0_5rem_-2rem_rgb(0_0_0_/_15%)]">
                    <div class="relative flex items-center max-w-[50rem] bg-gray-800 border-b border-gray-700 rounded-t-lg py-2 px-24">
                        <div class="flex space-x-1 absolute top-2/4 left-4 -translate-y-1">
                            <span class="w-2 h-2 bg-gray-700 rounded-full"></span>
                            <span class="w-2 h-2 bg-gray-700 rounded-full"></span>
                            <span class="w-2 h-2 bg-gray-700 rounded-full"></span>
                        </div>
                        <div class="flex justify-center items-center w-full h-full bg-gray-700 text-[.25rem] text-gray-200 rounded-sm sm:text-[.5rem]">www.preline.co</div>
                    </div>

                    <div class="bg-gray-800 rounded-b-lg">
                        <img class="max-w-full h-auto rounded-b-lg" src="./img/img10.jpg" alt="Image Description">
                    </div>
                </figure>
                <!-- End Browser Device -->
            </div>
            <!-- End Devices -->
        </div>

        <div id="tabs-with-card-3" class="hidden" role="tabpanel" aria-labelledby="tabs-with-card-item-3">
            <!-- Devices -->
            <div class="max-w-[1140px] lg:pb-32 relative">
                <!-- Mobile Device -->
                <figure class="hidden absolute bottom-0 left-0 z-[2] max-w-full w-60 h-auto mb-20 ml-20 lg:block">
                    <div class="p-1.5 bg-gray-100 rounded-3xl shadow-[0_2.75rem_5.5rem_-3.5rem_rgb(45_55_75_/_20%),_0_2rem_4rem_-2rem_rgb(45_55_75_/_30%),_inset_0_-0.1875rem_0.3125rem_0_rgb(45_55_75_/_20%)] dark:bg-gray-700 dark:shadow-[0_2.75rem_5.5rem_-3.5rem_rgb(0_0_0_/_20%),_0_2rem_4rem_-2rem_rgb(0_0_0_/_30%),_inset_0_-0.1875rem_0.3125rem_0_rgb(0_0_0_/_20%)]">
                        <img class="max-w-full h-auto rounded-[1.25rem]" src="./img/img13.jpg" alt="Image Description">
                    </div>
                </figure>
                <!-- End Mobile Device -->
                <!-- Browser Device -->
                <figure class="ml-auto mr-20 relative z-[1] max-w-full w-[50rem] h-auto rounded-b-lg shadow-[0_2.75rem_3.5rem_-2rem_rgb(45_55_75_/_20%),_0_0_5rem_-2rem_rgb(45_55_75_/_15%)] dark:shadow-[0_2.75rem_3.5rem_-2rem_rgb(0_0_0_/_20%),_0_0_5rem_-2rem_rgb(0_0_0_/_15%)]">
                    <div class="relative flex items-center max-w-[50rem] bg-white border-b border-gray-100 rounded-t-lg py-2 px-24 dark:bg-gray-800 dark:border-gray-700">
                        <div class="flex space-x-1 absolute top-2/4 left-4 -translate-y-1">
                            <span class="w-2 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></span>
                            <span class="w-2 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></span>
                            <span class="w-2 h-2 bg-gray-200 rounded-full dark:bg-gray-700"></span>
                        </div>
                        <div class="flex justify-center items-center w-full h-full bg-gray-200 text-[.25rem] text-gray-800 rounded-sm sm:text-[.5rem] dark:bg-gray-700 dark:text-gray-200">www.preline.co</div>
                    </div>

                    <div class="bg-gray-800 rounded-b-lg">
                        <img class="max-w-full h-auto rounded-b-lg" src="./img/img12.jpg" alt="Image Description">
                    </div>
                </figure>
                <!-- End Browser Device -->
            </div>
            <!-- End Devices -->
        </div>
    </div>
    <!-- End Tab Content -->
</div>
<!-- End Features -->

VioRentals.Web/Views/Home/Login.cshtml
@model VioRentals.Web.DTOs.LoginDto

@using (Html.BeginForm("Login", "Authenticate", FormMethod.Post))
{
    <main class="w-full max-w-md mx-auto p-6" style="min-height: 70vh;">
        <div class="mt-7 bg-white border border-gray-200 rounded-xl shadow-sm dark:bg-gray-800 dark:border-gray-700">
            <div class="p-4 sm:p-7">
                <div class="text-center">
                    <h1 class="block text-2xl font-bold text-gray-800 dark:text-white">Sign in</h1>
                    <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
                        Don't have an account yet?
                        <a class="text-blue-600 decoration-2 hover:underline font-medium" asp-controller="Home" asp-action="Register">
                            Sign up here
                        </a>
                    </p>
                </div>
                <div class="mt-5">
                    <!-- Form -->
                    <form>
                        <div class="grid gap-y-4">
                            <div>
                                @Html.TextBoxFor(model => model.Email, new { @class = "block w-full p-3 rounded bg-gray-100 border border-transparent dark:bg-gray-800 dark:text-gray-300 focus:outline-none focus:border-gray-400 focus:bg-white dark:focus:bg-gray-700 dark:focus:border-gray-600", @placeholder = "Email" })
                                <p class="hidden text-xs text-red-600 mt-2" id="email-error">Please include a valid email address so we can get back to you</p>
                            </div>
                            <div>
                                @Html.TextBoxFor(model => model.Password, new { @class = "block w-full p-3 rounded bg-gray-100 border border-transparent dark:bg-gray-800 dark:text-gray-300 focus:outline-none focus:border-gray-400 focus:bg-white dark:focus:bg-gray-700 dark:focus:border-gray-600", @placeholder = "Password" })
                                <p class="hidden text-xs text-red-600 mt-2" id="password-error">8+ characters required</p>
                            </div>
                            <button type="submit" class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800" value="Login">Sign in</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
}

VioRentals.Web/Views/Home/Register.cshtml
@model VioRentals.Web.DTOs.RegisterDto

@using (Html.BeginForm("Register", "Authenticate", FormMethod.Post))
{
    <main class="w-full max-w-md mx-auto p-6" style="min-height: 70vh;">
    <div class="mt-7 bg-white border border-gray-200 rounded-xl shadow-sm dark:bg-gray-800 dark:border-gray-700">
        <div class="p-4 sm:p-7">
            <div class="text-center">
                <h1 class="block text-2xl font-bold text-gray-800 dark:text-white">Sign up</h1>
                <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
                    Already have an account?
                        <a class="text-blue-600 decoration-2 hover:underline font-medium" asp-controller="Home" asp-action="Login">
                        Sign in here
                    </a>
                </p>
            </div>

            <div class="mt-5">
                <!-- Form -->
                <form>
                    <div class="grid gap-y-4">
                        <!-- Form Group -->
                        <div>
                            @Html.TextBoxFor(model => model.Forename, new { @class = "block w-full p-3 rounded bg-gray-100 border border-transparent dark:bg-gray-800 dark:text-gray-300 focus:outline-none focus:border-gray-400 focus:bg-white dark:focus:bg-gray-700 dark:focus:border-gray-600", @placeholder = "Forename" })
                            <p class="hidden text-xs text-red-600 mt-2" id="email-error">Please include a valid email address so we can get back to you</p>
                        </div>
                        <!-- End Form Group -->
                        <!-- Form Group -->
                        <div>
                            @Html.TextBoxFor(model => model.Lastname, new { @class = "block w-full p-3 rounded bg-gray-100 border border-transparent dark:bg-gray-800 dark:text-gray-300 focus:outline-none focus:border-gray-400 focus:bg-white dark:focus:bg-gray-700 dark:focus:border-gray-600", @placeholder = "Lastname" })
                            <p class="hidden text-xs text-red-600 mt-2" id="email-error">Please include a valid email address so we can get back to you</p>
                        </div>
                        <!-- End Form Group -->
                        <!-- Form Group -->
                        <div>
                            @Html.TextBoxFor(model => model.Email, new { @class = "block w-full p-3 rounded bg-gray-100 border border-transparent dark:bg-gray-800 dark:text-gray-300 focus:outline-none focus:border-gray-400 focus:bg-white dark:focus:bg-gray-700 dark:focus:border-gray-600", @placeholder = "Email" })
                            <p class="hidden text-xs text-red-600 mt-2" id="email-error">Please include a valid email address so we can get back to you</p>
                        </div>
                        <!-- End Form Group -->
                        <!-- Form Group -->
                        <div>
                            @Html.TextBoxFor(model => model.Password, new { @class = "block w-full p-3 rounded bg-gray-100 border border-transparent dark:bg-gray-800 dark:text-gray-300 focus:outline-none focus:border-gray-400 focus:bg-white dark:focus:bg-gray-700 dark:focus:border-gray-600", @placeholder = "Password" })
                            <p class="hidden text-xs text-red-600 mt-2" id="password-error">8+ characters required</p>
                        </div>
                        <!-- End Form Group -->

                        <button type="submit" class="py-3 px-4 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm dark:focus:ring-offset-gray-800" value="Register">Sign up</button>
                    </div>
                </form>
                <!-- End Form -->
            </div>
        </div>
    </div>
</main>
}